config/routes.rb
CuberootLts::Application.routes.draw do
  get "holidays/index"

  devise_for :users, :controllers => {:sessions => "sessions"}


  resources :leaves do
    member do
      get 'approve_reject', 'change_year', 'reject_approved_leaves'
    end
    collection do
      post 'set_year'
    end
  end


  resources :users do
    member do
      get 'user_management'
    end
  end

  resources :setups

  resources :holidays


root :to => "home#index"

end

app/models/holiday.rb
class Holiday < ActiveRecord::Base
  
  validate :holiday_cannot_be_on_weekends, :on => :create 
  # if holiday date is already present, it gives error message
  validates_uniqueness_of :date, :message => "Holiday is already present in list"
  # Admin should enter event textfield, it mustn't blank
  validates_presence_of :event, :message => "Event must not be blank"
 
  # while inserting holiday, it should not be on weekends 
  def holiday_cannot_be_on_weekends
    if (self.date.strftime("%u") == "6" or self.date.strftime("%u") == "7")
      errors.add(:date, "Holiday should not be on weekends")
    end
  end

end

app/controllers/holidays_controller.rb
class HolidaysController < ApplicationController

  # returns yearwise holiday list 
  def index
    @holidays_by_year = Holiday.find(:all, :conditions => ['year(date) = ?',  Time.now.year])
    if params[:commit] == "set"
      @holidays_by_year = Holiday.find(:all, :conditions => ['year(date) = ?', params[:date][:year]])
    end
  end

  # create new holiday entry and saves it in appropriate yearwise holiday list
  def create
    @holiday = Holiday.new(params[:holiday])

    respond_to do |format|
      if @holiday.save
        format.html { redirect_to holidays_index_path(@holiday), notice: 'Holiday is Submitted' }

      else
        format.html { render action: "new" }
      end
    end
  end

  # create new holiday entry
  def new
    @holiday = Holiday.new
    respond_to do |format|
      format.html
    end
  end

  # edit holiday date or holiday name
  def edit
    @holiday = Holiday.find(params[:id])
  end

  # show holiday
  def show
    @holiday = Holiday.find(params[:id])
    respond_to do |format|
      format.html
    end
  end

  # updates holiday date or holiday name and saves updated holiday
  def update
    @holiday = Holiday.find(params[:id])

    respond_to do |format|
      if @holiday.update_attributes(params[:holiday])
        format.html { redirect_to holiday_path(@holiday), notice: 'Holiday is successfully updated' }
      else
        format.html { render action: "edit" }
      end
    end
  end

  # delete holiday entry(in case)
  def destroy
    @holiday = Holiday.find_by_id(params[:id])
    @holiday.destroy
    flash[:notice] = 'Holiday is successfully deleted.'
    redirect_to :action => 'index'
  end

end

app/helpers/holidays_helper.rb
module HolidaysHelper
end

app/views/holidays/edit.html.erb
<h2>Edit Holiday List</h2>

<%= form_for @holiday do |f| %>
  <% @holiday.errors.full_messages.each do |msg| %>
    <p><%= msg %></p>
  <% end %>
  
  <div class="field">
    <%= f.label :Date %><br />
    <%= f.date_select :date %>
  </div>

  <div class="field">
    <%= f.label :Event %><br />
    <%= f.text_field :event %>
  </div>

  <div class="action">
    <%= f.submit %>
  </div>

<% end %>

<%= link_to 'Back', holidays_index_path %>
<!--
%h2 Edit Holiday List
= form_for @holiday, :url => { :action => "update" } do |f|
  .field
    = f.label :Date
    %br/
    = f.date_select :date
  .field
    = f.label :Event
    %br/
    = f.text_field :event
  .action
    = f.submit

= link_to 'Back', holidays_index_path

-- >

app/views/holidays/edit.html.haml
%h2 Edit Holiday List
= form_for @holiday, :url => { :action => "update" } do |f|
  -@holiday.errors.full_messages.each do |msg|
    %p= msg

  .field
    = f.label :Date
    %br/
    = f.date_select :date
  .field
    = f.label :Event
    %br/
    = f.text_field :event
  .action
    = f.submit

= link_to 'Back', holidays_index_path

app/views/holidays/index.html.haml
%h2 Holidays List
%table
  %tr
    %th Date
    %th Event

  - @holidays_by_year.each do |holiday|
    %tr
      %td= holiday.date
      %td= holiday.event
      - if current_user.role == 'admin'
        %td= link_to 'Edit', edit_holiday_path(holiday)
        %td= link_to 'Destroy', holiday, confirm: 'Are you sure?', method: :delete

=form_tag '/holidays', {:method => :get} do
  = label_tag :Holidays_by_year
  = select_year(Date.today)
  = submit_tag "set"

- if current_user.role == 'admin'
  = link_to 'Back', user_management_user_path(current_user.id)
  %br/
  %br/
  = link_to 'Insert Holiday', new_holiday_path
- else
  = link_to 'Back', leaves_path

app/views/holidays/new.html.haml
%h1 Enter Holiday 
= form_for @holiday do |f|
  -@holiday.errors.full_messages.each do |msg|
    %p= msg

  .field
    = f.label :Date
    = f.date_select :date
  .field
    = f.label :Event
    = f.text_field :event
  .action
    = f.submit

= link_to 'Back', holidays_index_path

app/views/holidays/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Date</b>
  <%= @holiday.date %>
</p>

<p>
  <b>Event</b>
  <%= @holiday.event %>
</p>

<br />

<%= link_to 'Back', holidays_index_path %>

<!--
%p#notice= notice

%p
  %b Date
  = @holiday.date

%p
  %b Event
  = @holiday.event

%br/

= link_to 'Back', holidays_index_path

-->

app/views/holidays/show.html.haml
%p#notice
= notice

%p
  %b Date
  = @holiday.date

%p
  %b Event
  = @holiday.event

%br/

= link_to 'Back', holidays_index_path