config/routes.rb
CuberootLts::Application.routes.draw do
  get "holidays/index"

  devise_for :users, :controllers => {:sessions => "sessions"}


  resources :leaves do
    member do
      get 'approve_reject', 'change_year', 'reject_approved_leaves'
    end
    collection do
      post 'set_year'
    end
  end


  resources :users do
    member do
      get 'user_management'
    end
  end

  resources :setups

  resources :holidays


root :to => "home#index"

end

app/models/setup.rb
class Setup < ActiveRecord::Base
# getter & setter for total_leaves and year 
attr_accessible :total_leaves, :year
# total_leaves & year must not be blank
validates_presence_of :total_leaves, :year
# total leaves should be positive integer
validates_numericality_of :total_leaves, 
                          :only_integer => true, 
                          :greater_than_or_equal_to => 0,
                          :maximum => 2,
                          :message => "Total leaves should be positive integers & must be greater than 0"
# year should be greater than 2010
validates_numericality_of :year, 
                          :only_integer => true, 
                          :greater_than_or_equal_to => 2011, 
                          :message => "Year should be 2011 or next of 2011"
# while inserting new entry, year should not be duplicated
validates_uniqueness_of :year, :message => "You have already added total holidays for this year"

  def self.get_remaining_leave
    remaining_leaves = self.total_leaves - @leaves_taken
    return remaining_leaves
  end

  def self.total_leave
    #connection = ActiveRecord::Base.connection();
    #query = ("select total_leaves from setups where year = '#{Time.now.year}'")

    #result = connection.execute(query)
    result = Setup.find_by_sql ("select total_leaves from setups where year = '#{Time.now.year}' ")
    #result = Setup.select("total_leaves").where(:year => "#{Time.now.year}%")

    return result
  end

end

app/controllers/setups_controller.rb
class SetupsController < ApplicationController
  # returns setup of leaves for all year
  def index
    @setups = Setup.all
  end

  # displays setup
  def show
    @setup = Setups.find(params[:id])
    respond_to do |format|
      format.html
    end
  end

  # create new setup
  def new
    @setup = Setup.new
    respond_to do |format|
      format.html
    end
  end

  # edit existing setup
  def edit
    @setup = Setup.find(params[:id])
  end

  # update setup details and saves updated details
  def update
    @setup = Setup.find(params[:id])
    respond_to do |format|
      if @setup.update_attributes(params[:setup])
        format.html { redirect_to setups_path, notice: 'Setup details successfully updated.' }
      else
        format.html { render action: "edit" }
      end
    end
  end

  # creates new setup entry and if it valids saves it.
  def create
    @setup = Setup.new(params[:setup])

    respond_to do |format|
      if @setup.save
        format.html { redirect_to setups_path, notice: 'Setup details Submitted' }
      else
        format.html { render action: "new" }
      end
    end
  end

  # delete existing setup
  def destroy
    @setup = Setup.find_by_id(params[:id])
    @setup.destroy
    flash[:notice] = 'Setup is successfully deleted.'
    redirect_to :action => 'index'
  end

end

app/helpers/setups_helper.rb
module SetupsHelper
end

app/views/setups/_leave_balance.html.erb
<h4>Total Leaves:
  <% @setups.each do |setup| %>
    <%= setup.total_leaves %>
  <% end %>
</h4>
<h4>Leaves Taken:
  <%= @leaves_taken %></h4>

<h4>Leaves Balance:
<% @setups.each do |setup| %>
    <%= setup.total_leaves - @leaves_taken %>
<% end %></h4>

app/views/setups/_leave_balance.html.haml
%h4
  Total Leaves:
  - @setups.each do |setup|
    = setup.total_leaves
%h4
  Leaves Taken:
  \#{@leaves_taken}
%h4
  Leaves Balance:
  - @setups.each do |setup|
    = setup.total_leaves - @leaves_taken

app/views/setups/edit.html.erb
<h2>Edit Setup</h2>

<%= form_for @setup, :url => { :action => "update" } do |f| %>
  <% @setup.errors.full_messages.each do |msg| %>
    <p><%= msg %></p>
  <% end %>

   <div class="field">
    <%= f.label :Total_leaves %><br />
    <%= f.text_field :total_leaves %>
  </div>

  <div>
    <%= f.label :Year %><br />
    <%= f.text_field :year %>
  </div>

  <div>
    <%= f.submit %>
  </div>

<% end %>

<%= link_to 'Back', setups_path %>

app/views/setups/edit.html.haml
%h2 Edit Setup
= form_for @setup, :url => { :action => "update" } do |f|
  - @setup.errors.full_messages.each do |msg|
    %p= msg
  .field
    = f.label :Total_leaves
    %br/
    = f.text_field :total_leaves
  .field
    = f.label :Year
    %br/
    = f.text_field :year
  .actions
    = f.submit
= link_to 'Back', setups_path

app/views/setups/index.html.erb
<h3>Setup</h3>

<table>
  <tr>
    <th>Total Leaves</th>
    <th>Year</th>
  </tr>

  <% @setups.each do |setup| %>
    <tr>
      <td><%= setup.total_leaves %></td>
      <td><%= setup.year %></td>
      <td><%= link_to 'Edit', edit_setup_path(setup) %></td>
      <td><%= link_to 'Destroy', setup, confirm: 'Are you sure?', method: :delete %></td>
    </tr>
  <% end %>
</table>

<p>
  <%= link_to 'New Entry', new_setup_path %>
</p>

<p>
  <%= link_to 'Back', user_management_user_path(current_user.id) %>
</p>

app/views/setups/index.html.haml
%h3 Setup
%table
  %tr
    %th Total Leaves
    %th Year
  - @setups.each do |setup|
    %tr
      %td= setup.total_leaves
      %td= setup.year
      %td= link_to 'Edit', edit_setup_path(setup)
      %td= link_to 'Destroy', setup, confirm: 'Are you sure?', method: :delete
%p
  = link_to 'New Entry', new_setup_path
%p
  = link_to 'Back', user_management_user_path(current_user.id)

app/views/setups/new.html.erb
<%= form_for @setup, :url => { :action => "create" }   do |f| %>
  <% @setup.errors.full_messages.each do |msg| %>
    <p><%= msg %></p>
  <% end %>

  <div class="field">
    <%= f.label :total_leaves %>
    <%= f.text_field :total_leaves %>
  </div>

  <div class="field">
    <%= f.label :year %>
    <%= f.text_field :year %>
  </div>

  <div class="action">
    <%= f.submit "Save" %>
  </div>

<% end %>

<p>
  <%= link_to 'Back', setups_path(current_user.id) %>
</p>

app/views/setups/new.html.haml
= form_for @setup, :url => { :action => "create" }   do |f|
  - @setup.errors.full_messages.each do |msg|
    %p= msg
  .field
    = f.label :total_leaves
    = f.text_field :total_leaves
  .field
    = f.label :year
    = f.text_field :year
  .action
    = f.submit "Save"
%p
  = link_to 'Back', setups_path(current_user.id)