config/routes.rb
CuberootLts::Application.routes.draw do
  get "holidays/index"

  devise_for :users, :controllers => {:sessions => "sessions"}


  resources :leaves do
    member do
      get 'approve_reject', 'change_year', 'reject_approved_leaves'
    end
    collection do
      post 'set_year'
    end
  end


  resources :users do
    member do
      get 'user_management'
    end
  end

  resources :setups

  resources :holidays


root :to => "home#index"

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  before_save :totalleaves

  has_many :leaves, :dependent => :destroy
# validates_associated :leaves
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  belongs_to :manager, :class_name => "User", :foreign_key => 'manager_id'
  
  validates :email,
            :presence => true,
            :uniqueness => true,
            :format => { :with => /^[-a-z0-9_+\.]+\@(cuberoot\.in)$/i, :message => "should be a cuberoot.in email" }


   # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :manager_id, :joining_date, :role

  scope :managers, where(:role => 'manager')
  scope :non_admins, where(:role => ['manager', 'employee'])

  def totalleaves
    @setup = Setup.find(:all, :conditions =>['year = ?', "#{Time.now.year}"])
    @setup.each do |s|
      leave_per_month = (s.total_leaves.to_f/12.to_f).to_f
      month_by_no = self.joining_date.strftime("%m")
      leave_per_employee = (( 12 - (month_by_no.to_i - 1 ).to_f) * (leave_per_month.to_f )).to_f
      self.total_leaves = leave_per_employee.to_f
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  #returns all users list 
  def index
    @users = User.all
      respond_to do |format|
      format.html
    end
  end

  # edit user details
  def edit
    @user= User.find(params[:id])
  end

  # update user details and saves updated details
  def update
    @setup = Setup.find(:all, :conditions => ['year = ?', "#{Time.now.year}"])
    @user = User.find(params[:id])
    if params[:commit] == "Change"
      @user.manager_id = params[:manager_id]
      @user.joining_date = params[:joining_date]
      @user.role = params[:role]
    end

    if @user.update_attributes(params[:user])
      redirect_to @user, :notice => 'Employees info has changed'
    else
      Rails.logger.info(@user.errors.messages.inspect)
      render :edit
    end
  end

  # shows user details
  def show
    @user = User.find(params[:id])
    respond_to do |format|
      format.html
    end
  end

  # returns all users except admin
  def user_management
    @users = User.non_admins
    #@users = User.find(:all, :conditions => ['id = ?' , "#{current_user.manager_id}%"])
    respond_to do |format|
      format.html
    end
  end

  def destroy
    @user = User.find_by_id(params[:id])
    @user.destroy
    flash[:notice] = 'User is successfully deleted.'
    #redirect_to :action => 'user_management', :id=>session[:user_id]
    redirect_to user_management_user_path(current_user.id)
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<h2>Edit Employee's Information</h2>

<%= form_for @user, :url => { :action => "update" } do |f| %>
  <% @user.errors.full_messages.each do |msg| %>
    <p><%= msg %></p>
  <% end %>

   <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div><br />

  <div class="field">
    <%= f.label :manager_id %><br />
    <%= f.select("manager_id", User.managers.collect {|p| [p.email, p.id] }) %>
  </div><br />

  <div class="field">
    <%= f.radio_button :role, 'employee' %>Employee
    <%= f.radio_button :role, 'manager' %>Manager
  </div>

  <div class="field">
    <%= f.label :Joining_Date %>
    <%= f.date_select :joining_date %>
  </div>

  <div class="action">
    <%= f.submit "Change" %><br />
  </div><br />

<% end %>

<br />

<%= link_to 'Back', user_management_user_path(current_user.id) %>

app/views/users/edit.html.haml
%h2 Edit Employee's Information
= form_for @user, :url => { :action => "update" } do |f|
  - @user.errors.full_messages.each do |msg|
    %p= msg
  .field
    = f.label :email
    %br/
    = f.text_field :email
  %br/
  .field
    = f.label :manager_id
    %br/
    = f.select("manager_id", User.managers.collect {|p| [p.email, p.id] })
  %br/
  .field
    = f.radio_button :role, 'employee'
    Employee
    \#{f.radio_button :role, 'manager'}Manager
  .field
    = f.label :Joining_Date
    = f.date_select :joining_date
  .action
    = f.submit "Change"
    %br/
  %br/
%br/
= link_to 'Back', user_management_user_path(current_user.id)

app/views/users/show.html.erb
<p>
  <b>Manager</b>
  <%= @user.manager.email %>
</p>

<p>
  <b>Joining Date</b>
  <%= @user.joining_date %>
</p>

<p>
  <b>Total Leaves</b>
  <%= @user.total_leaves %>
</p>



<%= link_to 'Back', user_management_user_path(current_user.id) %>

app/views/users/show.html.haml
%p
  %b Manager
  = @user.manager.email
%p
  %b Joining Date
  = @user.joining_date
%p
  %b Total Leaves
  = @user.total_leaves
= link_to 'Back', user_management_user_path(current_user.id)

app/views/users/user_management.html.erb
<h2>Welcome Admin</h2>
<br />
<table>
  <caption>User Management</caption>
  <tr>
    <th>Employee</th>
    <th>Reporting Manager</th>
  </tr>

  <% @users.each do |user| %>
    <tr>
      <td><%= user.email %></td>
      <td><%= user.manager.email %></td>
      <td><%= link_to 'Edit', edit_user_path(user.id) %></td>
      <td><%= link_to 'Destroy', user, confirm: 'Are you sure?', method: :delete %></td>
    </tr>
  <% end %>
</table>

<%= link_to "Setup for Leaves", setups_path %><br />

<%= link_to "Manage Holiday List", holidays_index_path %>

app/views/users/user_management.html.haml
%h2 Welcome Admin
%br/
%table
  %caption User Management
  %tr
    %th Employee
    %th Reporting Manager
  - @users.each do |user|
    %tr
      %td= user.email
      %td= user.manager.email
      %td= link_to 'Edit', edit_user_path(user.id)
      %td= link_to 'Destroy', user, confirm: 'Are you sure?', method: :delete
= link_to "Setup for Leaves", setups_path
%br/
= link_to "Manage Holiday List", holidays_index_path