config/routes.rb
CuberootLts::Application.routes.draw do
  get "holidays/index"

  devise_for :users, :controllers => {:sessions => "sessions"}


  resources :leaves do
    member do
      get 'approve_reject', 'change_year', 'reject_approved_leaves'
    end
    collection do
      post 'set_year'
    end
  end


  resources :users do
    member do
      get 'user_management'
    end
  end

  resources :setups

  resources :holidays


root :to => "home#index"

end

app/models/leave.rb
class Leave < ActiveRecord::Base
  # Leave belongs to user and user has many leaves
  belongs_to :user
  # before save,no of days for leave calculated
  before_save :no_of_days_for_leave
  # while applying leave start date of leave must be less than end date of leave
  validate :startdate_cannot_be_greater_than_enddate, :on => :create
  # user must have give reason for taking leave 
  validates_presence_of :reason, :on => :create, :message => "must not be blank"
  
  # end date of leave must be greater than start date of leave
  def startdate_cannot_be_greater_than_enddate
    if (self.start_date > self.end_date)
      errors.add(:start_date, "must be earlier than end date")
    end
  end

  # no of days for leave automatically calculated, excluding weekends and holidays
  def no_of_days_for_leave
    @govt_holiday = Holiday.where(["date between ? and ? ", start_date, end_date]).count

    business_days = connection.select_all("select uGetBussinessDays('#{start_date}','#{end_date}') as bd").first

    self.no_of_days = business_days['bd'].to_i - @govt_holiday

  end


  def validate_leave_details(year)
    self # leave

    @setup = Setup.where(['year = ?', Time.now.year]).first
    if @setup.total_leaves >= Leave.where(:current_status => "Approved").where(:user_id => self.user_id).sum(:no_of_days)
      true
    else
      false
    end
  end

end

app/controllers/leaves_controller.rb
class LeavesController < ApplicationController

  # creates new leave and saves it.
  def create
    @leave = current_user.leaves.build(params[:leave])
    @leave.current_status = "Pending"

    respond_to do |format|
      if @leave.save
       # LeaveMailer.leave_email(@leave).deliver
        format.html { redirect_to leave_path(@leave), notice: 'Leave is Submitted' }
      else
        format.html { render action: "new" }
      end
    end
  end

  # new leave entry
  def new
    @leave = Leave.new
    respond_to do |format|
      format.html
    end
  end

  # edits leave details
  def edit
    @leave = Leave.find(params[:id])
  end

  # updates leave details and saves updates leave details
  def update
    @leave = Leave.find( params[:id])

    if params[:commit] == "Approve"
        @leave.current_status = "Approved"
        @leave.approved_by = current_user.id
        @leave.approved_on = Time.now
    end

    if params[:commit] == "Reject"
      @leave.current_status = "Rejected"
      @leave.approved_by = current_user.id
      @leave.rejection_reason = params[:rejection_reason]
    end
    
    if params[:commit] == "Reject (in case)"
      @leave.current_status = "Rejected"
    end
    
    respond_to do |format|
      if @leave.update_attributes(params[:leave])
        format.html { redirect_to leave_path(@leave), notice: 'Leave is successfully updated.' }
      else
        debugger
        format.html { render action: "edit" }
      end
    end
  end

  def validate_leave_details
    @setup = Setup.where(['year = ?', Time.now.year]).first
    debugger
    @setup.each do |setup|
      if setup.total_leaves >= Leave.where(:current_status => "Approved").where(:user_id => "#{@leave.user_id}%").sum(:no_of_days)
        debugger
        flash[:notice] = "Hello world!"
      else
        return false
      end
    end
  end

  # delete applied leave
  def destroy
    @leave = Leave.find_by_id(params[:id])
    @leave.destroy
    flash[:notice] = 'Leave is successfully deleted.'
    redirect_to :action => 'index', :id=>session[:user_id]
  end

  # returns all leaves associated with user
  def index
    if current_user.role == 'manager'
      @leaves = Leave.find(:all, :conditions => ['user_id = ? and year(start_date) = ?', current_user.id, session[:current_year]])
      #@leaves = current_user.leaves

      #@subordinates = User.where(:manager_id => current_user.id)
      #@subordinates.each do |subordinate|
       # @subordinates_leaves = Leave.find(:all, :conditions => ['user_id => ?', subordinate.user_id])
      #end

       # subordinate.leaves
      #end
    else
      @leaves = Leave.find(:all, :conditions => ['user_id = ? and year(start_date) = ?', current_user.id, session[:current_year]])
    end
    @leaves_taken = Leave.where(['user_id = ? and current_status = ? and year(start_date) = ?', current_user.id, "Approved", session[:current_year]]).sum(:no_of_days)

    #@leaves_taken = Leave.where(:current_status => "Approved").where(:user_id => "#{current_user.id}%").sum(:no_of_days)
    @setups = Setup.select("total_leaves").where(:year => session[:current_year])
    @users = User.find(:all, :conditions => ['id = ?' , "#{current_user.manager_id}%"])
  end

  # displays applied leave
  def show
    @leave = Leave.find(params[:id])
    respond_to do |format|
      format.html
    end
  end

  # manager can approve/reject leave of employees under him/her
  def approve_reject
    @leaves = Leave.find(:all, :conditions =>['user_id = ? and current_status = ?', params[:user_id].to_i, 'Approved'])
    @leave = Leave.find(params[:id])

    respond_to do |format|
      format.html
    end
  end

  def change_year
  end

  # returns leaves history as per year
  def set_year
    if params[:commit] = "set"
      session[:current_year] = params[:date][:year]
      redirect_to leaves_url
    end
  end

 end

app/helpers/leaves_helper.rb
module LeavesHelper
end

app/views/leaves/_approved_leaves.html.haml
%br/
%hr/
%br/
%table
  %caption
    Approved Leaves of #{current_user.email}
  %tr
    %th Applied_on
    %th No_of_days
    %th Start_date
    %th End_Date
    %th Approved_on
    %th Approved_by
   
  - @leaves.each do |leave|
    - if leave.current_status == "Approved"
      %tr
        %td= leave.created_at.strftime("%d-%m-%Y")
        %td= leave.no_of_days
        %td= leave.start_date.strftime("%d-%m-%Y")
        %td= leave.end_date.strftime("%d-%m-%Y")
        %td= leave.updated_at.strftime("%d-%m-%Y")
        %td
          - @users.each do |user|
            = leave.user.manager.email

%br/
%hr/
%br/
= link_to "Apply for Leave", new_leave_path, :class => 'btn'
%br/
%br/
%p
  = link_to "Holidays List", holidays_index_path

app/views/leaves/_form.html.erb
<br />
<hr />
<br />
<table>
  <caption>Approved Leaves of <%= current_user.email %></caption>
  <tr>
    <th>Applied_on</th>
    <th>No_of_Days</th>
    <th>Start_date</th>
    <th>End_date</th>
    <th>Approved_on</th>
    <th>Approved_by</th>
    <!--<% if current_user.role == 'manager' %>
      <th>Email</th>
    <% end %>-->
   </tr>

   <% @leaves.each do |leave| %>
     <% if leave.current_status == "Approved" %>
        <tr>
          <td><%= leave.created_at.strftime("%d-%m-%Y") %></td>
          <td><%= leave.no_of_days %></td>
          <td><%= leave.start_date.strftime("%d-%m-%Y") %></td>
          <td><%= leave.end_date.strftime("%d-%m-%Y") %></td>
          <td><%= leave.updated_at.strftime("%d-%m-%Y") %></td>
          <td><% @users.each do |user|%>
                <%= leave.user.manager.email %>
              <% end %>
          </td>
          <!--<% if current_user.role == 'manager'%>
          <td><%= leave.user.email %></td>-->
            <% end %>-->
      </tr>
      <% end %>
    <% end %>
</table>

<br />
<hr />
<br />
<%= link_to "Apply for Leave", new_leave_path, :class => 'btn' %>
<br />
<br />

<%= link_to "Holiday List", holidays_index_path %>


<!--
%h4 Approved Leaves
%table
  %tr
    %th Applied_on
    %th No_of_days
    %th Start_date
    %th End_Date
    %th Approved_on
    %th Approved_by
    - if current_user.role == 'manager'
      %th Email

  - @leaves.each do |leave|
    - if leave.current_status == "Approved"
      %tr
        %td= leave.created_at.strftime("%d-%m-%Y")
        %td= leave.no_of_days
        %td= leave.start_date
        %td= leave.end_date
        %td= leave.updated_at.strftime("%d-%m-%Y")
        %td
          - @users.each do |user|
            = leave.user.manager_id
        - if current_user.role == 'manager'
          %td= leave.user.email

= link_to "Apply for Leave", new_leave_path
%br/

%p
  = link_to "Holidays List", Holidays_index_path

-->

app/views/leaves/approve_reject.html.haml
%h2 Managers Dashboard - Approve/Reject leave
%h3 Action
Employee Name:- #{@leave.user.email}
%br/
No_of_days:- #{@leave.no_of_days}
%br/
Start_date:- #{@leave.start_date}
%br/
End_date:- #{@leave.end_date}
%br/

%h2 Leaves_History
%table
  %tr
    %th Employee_id
    %th Applied_on
    %th No_of_Days
    %th Start_date
    %th End_date
    %th Approved_on
    %th Approved_by
  - @leaves.each do |leave|
  %tr
    %td= leave.user_id
    %td= leave.no_of_days
    %td= leave.start_date
    %td= leave.end_date
    %td= leave.updated_at
    %td= current_user.email

%br/
= form_for @leave, :url => { action => "update" } do |f|
  .actions
    = f.submit "Approve", :user_id => @leave
  .actions
    = f.submit "Reject"
  .field
    = f.label :rejection_reason
    = f.text_field :rejection_reason

%br/
= link_to 'Back', leaves_path

app/views/leaves/change_year.html.haml
= form_tag '/leaves/set_year' do 
  = label_tag :leaves_by_year 
  = select_year(Date.today)
  = submit_tag "set" 

app/views/leaves/index.html.erb
<%= content_for :sidebar do %>
  <%= render '/setups/leave_balance' %>
<% end %>

<h2>Employee's DashBoard:-</h2>
<table>
  <caption>Pending Leaves of <%= current_user.email %></caption>
  <tr>
    <th>Applied_on</th>
    <th>No_of_Days</th>
    <th>Start_date</th>
    <th>End_date</th>
    <th>Current_status</th>
    <!-- <% if current_user.role == 'manager'%>
      <th>Employee</th>
      <th>Action</th>
    <% end %>-->
  </tr>

    <% @leaves.each do |leave| %>
      <% if leave.current_status == "Pending" %>
        <tr>
          <td><%= leave.created_at.strftime("%d-%m-%Y") %></td>
          <td><%= leave.no_of_days %></td>
          <td><%= leave.start_date.strftime("%d-%m-%Y") %></td>
          <td><%= leave.end_date.strftime("%d-%m-%Y") %></td>
          <td><%= leave.current_status %></td>
          <!--<% if current_user.role == 'manager'%>
            <td><%= leave.user.email %></td>
            <td>
              <%= link_to 'Approve/Reject', approve_reject_leave_path(:id => leave.id, :user_id => leave.user.id)%>
            </td>
          <% end %> -->
        </tr>
      <% end %>
    <% end %>
</table>

<br />
<hr />
<br />

<table>
  <caption>Rejected Leaves of <%= current_user.email %></caption>
  <tr>
    <th>Applied_on</th>
    <th>No_of_Days</th>
    <th>Start_date</th>
    <th>End_date</th>
    <th>Current_status</th>
    <!-- <% if current_user.role == 'manager'%>
      <th>Employee</th>
      <th>Action</th>
    <% end %>-->
  </tr>

    <% @leaves.each do |leave| %>
      <% if leave.current_status == "Rejected" %>
        <tr>
          <td><%= leave.created_at.strftime("%d-%m-%Y") %></td>
          <td><%= leave.no_of_days %></td>
          <td><%= leave.start_date.strftime("%d-%m-%Y") %></td>
          <td><%= leave.end_date.strftime("%d-%m-%Y") %></td>
          <td><%= leave.current_status %></td>
          <!--<% if current_user.role == 'manager'%>
            <td><%= leave.user.email %></td>
            <td>
              <%= link_to 'Approve/Reject', approve_reject_leave_path(:id => leave.id, :user_id => leave.user.id)%>
            </td>
          <% end %> -->
        </tr>
      <% end %>
    <% end %>
</table>


<%= render 'form' %>

<% if current_user.role == 'manager' %>
  <table>
    <caption>Pending leaves of employees</caption>
    <tr>
      <th>Applied_on</th>
      <th>No_of_Days</th>
      <th>Start_date</th>
      <th>End_date</th>
      <th>Current_status</th>
      <th>Employee</th>
      <th>Action</th>
    </tr>

  <% @subordinates = User.where(:manager_id => current_user.id) %>
  <% @subordinates.each do |subordinate| %>
    <% @subordinates_leaves = subordinate.leaves %>
    <% @subordinates_leaves.each do |leave| %>
      <% if leave.current_status == "Pending" %>
      <tr>
        <td><%= leave.created_at.strftime("%d-%m-%Y") %></td>
        <td><%= leave.no_of_days %></td>
        <td><%= leave.start_date.strftime("%d-%m-%Y") %></td>
        <td><%= leave.end_date.strftime("%d-%m-%Y") %></td>
        <td><%= leave.current_status %></td>
        <td><%= leave.user.email %></td>
        <td>
          <%= link_to 'Approve/Reject', approve_reject_leave_path(:id => leave.id, :user_id => leave.user.id)%>
        </td> 
      </tr>
    <% end %>
    <% end %>
  <% end %>
</table>

<br />
<hr />
<br />

<table>
  <caption>Approved Leaves of employees</caption>
  <tr>
    <th>Applied_on</th>
    <th>No_of_Days</th>
    <th>Start_date</th>
    <th>End_date</th>
    <th>Approved_on</th>
    <th>Email</th>
    <th></th>
   </tr>
   
   <% @subordinates = User.where(:manager_id => current_user.id) %>
   <% @subordinates.each do |subordinate| %>
      <% @subordinates_leaves = subordinate.leaves %>
      <% @subordinates_leaves.each do |leave| %>
      <% if leave.current_status == "Approved" %>
        <tr>
          <td><%= leave.created_at.strftime("%d-%m-%Y") %></td>
          <td><%= leave.no_of_days %></td>
          <td><%= leave.start_date.strftime("%d-%m-%Y") %></td>
          <td><%= leave.end_date.strftime("%d-%m-%Y") %></td>
          <td><%= leave.updated_at.strftime("%d-%m-%Y") %></td>
          <td><%= leave.user.email %></td>
          <td><%= button_to 'Reject (in case)', {:action => :update, :id => leave.id, :commit => "Reject (in case)"}, :method => :put %></td>
        </tr>
      <% end %>
    <% end %>
  <% end %>
</table>

<br />
<hr />
<br />

<table>
  <caption>Rejected Leaves of employees</caption>
  <tr>
    <th>Applied_on</th>
    <th>No_of_Days</th>
    <th>Start_date</th>
    <th>End_date</th>
    <th>Approved_on</th>
    <th>Email</th>
  </tr>
   
   <% @subordinates = User.where(:manager_id => current_user.id) %>
   <% @subordinates.each do |subordinate| %>
      <% @subordinates_leaves = subordinate.leaves %>
      <% @subordinates_leaves.each do |leave| %>
      <% if leave.current_status == "Rejected" %>
        <tr>
          <td><%= leave.created_at.strftime("%d-%m-%Y") %></td>
          <td><%= leave.no_of_days %></td>
          <td><%= leave.start_date.strftime("%d-%m-%Y") %></td>
          <td><%= leave.end_date.strftime("%d-%m-%Y") %></td>
          <td><%= leave.updated_at.strftime("%d-%m-%Y") %></td>
          <td><%= leave.user.email %></td>
        </tr>
      <% end %>
    <% end %>
  <% end %>
</table>

<% end %>

<!--
= render '/setups/leave_balance'
%h2 Employee's DashBoard
%h4 Leaves Pending for Approval:-
%table
  %tr
    %th Applied_on
    %th No_of_Days
    %th Start_date
    %th End_date
    %th Current_status
    - if current_user.role == "manager"
      %th Employee
      %th Action

   - @leaves.each do |leave|
    - if leave.current_status == "Pending"
      %tr
        %td= leave.created_at.strftime("%d-%m-%Y")
        %td= leave.no_of_days
        %td= leave.start_date
        %td= leave.end_date
        %td= leave.current_status
        - if current_user.role == 'manager'
          %td= leave.user.email
          %td= link_to 'Approve/Reject', approve_reject_leave_path(:id => leave.id, :user_id => leave.user.id)
= render 'form'
-->

app/views/leaves/index.html.haml
= content_for :sidebar do
  = render '/setups/leave_balance'
%h2 Employee's DashBoard
%table
  %caption
    Pending Leaves of #{current_user.email}
  %tr
    %th Applied_on
    %th No_of_Days
    %th Start_date
    %th End_date
    %th Current_status
    
  - @leaves.each do |leave|
    - if leave.current_status == "Pending"
      %tr
        %td= leave.created_at.strftime("%d-%m-%Y")
        %td= leave.no_of_days
        %td= leave.start_date.strftime("%d-%m-%Y")
        %td= leave.end_date.strftime("%d-%m-%Y")
        %td= leave.current_status

%br/
%hr/
%br/
%table
  %caption
    Rejected Leaves of #{current_user.email}
  %tr
    %th Applied_on
    %th No_of_Days
    %th Start_date
    %th End_date
    %th Current_status
  - @leaves.each do |leave|
    - if leave.current_status == "Rejected"
      %tr
        %td= leave.created_at.strftime("%d-%m-%Y")
        %td= leave.no_of_days
        %td= leave.start_date.strftime("%d-%m-%Y")
        %td= leave.end_date.strftime("%d-%m-%Y")
        %td= leave.current_status

= render 'approved_leaves'

- if current_user.role == 'manager'
  %table
    %caption
      Pending Leaves of employees
    %tr
      %th Applied_on
      %th No_of_Days
      %th Start_date
      %th End_date
      %th Current_status
      %th Employee
      %th Action

    - @subordinates = User.where(:manager_id => current_user.id)
    - @subordinates.each do |subordinate|
      - @subordinates_leaves = subordinate.leaves
      - @subordinates_leaves.each do |leave|
        - if leave.current_status == "Pending"
          %tr
            %td= leave.created_at.strftime("%d-%m-%Y")
            %td= leave.no_of_days
            %td= leave.start_date.strftime("%d-%m-%Y")
            %td= leave.end_date.strftime("%d-%m-%Y")
            %td= leave.current_status
            %td= leave.user.email
            %td
              = link_to 'Approve/Reject', approve_reject_leave_path(:id => leave.id, :user_id => leave.user.id)

  %br/
  %table
    %caption
      Approved Leaves of employees
    %tr
      %th Applied_on
      %th No_of_Days
      %th Start_date
      %th End_date
      %th Approved_on
      %th Email
      %th 

    - @subordinates = User.where(:manager_id => current_user.id)
    - @subordinates.each do |subordinate|
      - @subordinates_leaves = subordinate.leaves
      - @subordinates_leaves.each do |leave|
        - if leave.current_status == "Approved"
          %tr
            %td= leave.created_at.strftime("%d-%m-%Y")
            %td= leave.no_of_days
            %td= leave.start_date.strftime("%d-%m-%Y")
            %td= leave.end_date.strftime("%d-%m-%Y")
            %td= leave.updated_at.strftime("%d-%m-%Y")
            %td= leave.user.email
            %td= button_to 'Reject (in case)', {:action => :update, :id => leave.id, :commit => "Reject (in case)"}, :method => :put

  %br/
  %hr/
  %br/
  %table
    %caption
      Rejected Leaves of employees
    %tr
      %th Applied_on
      %th No_of_Days
      %th Start_date
      %th End_date
      %th Approved_on
      %th Email

    - @subordinates = User.where(:manager_id => current_user.id)
    - @subordinates.each do |subordinate|
      - @subordinates_leaves = subordinate.leaves
      - @subordinates_leaves.each do |leave|
        - if leave.current_status == "Rejected"
          %tr
            %td= leave.created_at.strftime("%d-%m-%Y")
            %td= leave.no_of_days
            %td= leave.start_date.strftime("%d-%m-%Y")
            %td= leave.end_date.strftime("%d-%m-%Y")
            %td= leave.updated_at.strftime("%d-%m-%Y")
            %td= leave.user.email

app/views/leaves/new.html.haml
%h4 Apply For Leave:-
= form_for @leave, :url => { :action => "create" } do |f|
  - @leave.errors.full_messages.each do |msg|
    %p= msg
  .field-sDate
    = f.label :start_date
    %br/
    = f.date_select :start_date, :order => [:month, :day, :year]
  %hr/
  .field-eDate
    = f.label :end_date
    %br/
    = f.date_select :end_date, :order => [:month, :day, :year]
  .field-reason
    = f.label :reason
    %br/
    = f.text_area :reason
  %hr/
  .actions
    = f.submit

%hr/

=link_to 'Back', leaves_path

app/views/leaves/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Applied_On</b>
  <%=l @leave.created_at %>
</p>

<p>
  <b>start_date</b>
  <%=l @leave.start_date %>
</p>

<p>
  <b>end_date</b>
  <%=l @leave.end_date %>
</p>

<p>
  <b>no_of_days</b>
  <%= @leave.no_of_days %>
</p>

<p>
  <b>current_status</b>
  <%= @leave.current_status %>
</p>

<p>
  <%= link_to 'Back', leaves_path %>
</p>

app/views/leaves/show.html.haml
%p#notice
= notice
%p
  %b Applied_On
  =l @leave.created_at
%p
  %b start_date
  =l @leave.start_date
%p
  %b end_date
  = @leave.end_date
%p
  %b no_of_days
  = @leave.no_of_days
%p
  %b current_status
  = @leave.current_status
%p
  = link_to 'Back', leaves_path